export const interestsData = [
  { label: "Reading", value: "Reading" },
  { label: "Writing", value: "Writing" },
  { label: "Drawing", value: "Drawing" },
  { label: "Painting", value: "Painting" },
  { label: "Photography", value: "Photography" },
  { label: "Coding", value: "Coding" },
  { label: "Gaming", value: "Gaming" },
  { label: "Cooking", value: "Cooking" },
  { label: "Baking", value: "Baking" },
  { label: "Hiking", value: "Hiking" },
  { label: "Cycling", value: "Cycling" },
  { label: "Running", value: "Running" },
  { label: "Swimming", value: "Swimming" },
  { label: "Yoga", value: "Yoga" },
  { label: "Dancing", value: "Dancing" },
  { label: "Singing", value: "Singing" },
  { label: "Playing Musical Instruments", value: "Playing Musical Instruments" },
  { label: "Acting", value: "Acting" },
  { label: "Volunteering", value: "Volunteering" },
  { label: "Gardening", value: "Gardening" },
  { label: "Traveling", value: "Traveling" },
  { label: "Collecting", value: "Collecting" },
  { label: "Martial Arts", value: "Martial Arts" },
  { label: "Chess", value: "Chess" },
  { label: "Board Games", value: "Board Games" },
  { label: "Puzzle Solving", value: "Puzzle Solving" },
  { label: "Fishing", value: "Fishing" },
  { label: "Bird Watching", value: "Bird Watching" },
  { label: "Blogging", value: "Blogging" },
  { label: "Podcasting", value: "Podcasting" },
  { label: "Graphic Design", value: "Graphic Design" },
  { label: "Robotics", value: "Robotics" },
  { label: "Astronomy", value: "Astronomy" },
  { label: "Environmental Activism", value: "Environmental Activism" },
  { label: "Anime", value: "Anime" },
  { label: "Manga", value: "Manga" },
  { label: "Cosplay", value: "Cosplay" },
  { label: "Skateboarding", value: "Skateboarding" },
  { label: "Surfing", value: "Surfing" },
  { label: "Snowboarding", value: "Snowboarding" },
  { label: "Rock Climbing", value: "Rock Climbing" },
  { label: "Weightlifting", value: "Weightlifting" },
  { label: "Soccer", value: "Soccer" },
  { label: "Basketball", value: "Basketball" },
  { label: "Baseball", value: "Baseball" },
  { label: "Football", value: "Football" },
  { label: "Tennis", value: "Tennis" },
  { label: "Badminton", value: "Badminton" },
  { label: "Table Tennis", value: "Table Tennis" },
  { label: "Golf", value: "Golf" },
  { label: "Archery", value: "Archery" },
  { label: "Fencing", value: "Fencing" },
  { label: "Horseback Riding", value: "Horseback Riding" },
  { label: "Dance", value: "Dance" },
  { label: "Drama", value: "Drama" },
  { label: "Music Production", value: "Music Production" },
  { label: "DJing", value: "DJing" },
  { label: "Videography", value: "Videography" },
  { label: "Filmmaking", value: "Filmmaking" },
  { label: "3D Modeling", value: "3D Modeling" },
  { label: "Animation", value: "Animation" },
  { label: "Virtual Reality", value: "Virtual Reality" },
  { label: "Augmented Reality", value: "Augmented Reality" },
  { label: "Entrepreneurship", value: "Entrepreneurship" },
  { label: "Public Speaking", value: "Public Speaking" },
  { label: "Debate", value: "Debate" },
];



export const classData = [
  { label: "2028", value: "2028" },
  { label: "2027", value: "2027" },
  { label: "2026", value: "2026" },
  { label: "2025", value: "2025" },
  { label: "2024", value: "2024" },
  { label: "2023", value: "2023" },
  { label: "2022", value: "2022" },
  { label: "2021", value: "2021" },
  { label: "2020", value: "2020" },
  { label: "2019", value: "2019" },
  { label: "2018", value: "2018" },
  { label: "2017", value: "2017" },
  { label: "2016", value: "2016" },
  { label: "2015", value: "2015" },
  { label: "2014", value: "2014" },
  { label: "2013", value: "2013" },
  { label: "2012", value: "2012" },
  { label: "2011", value: "2011" },
  { label: "2010", value: "2010" },
  { label: "2009", value: "2009" },
  { label: "2008", value: "2008" },
  { label: "2007", value: "2007" },
  { label: "2006", value: "2006" },
  { label: "2005", value: "2005" },
  { label: "2004", value: "2004" },
  { label: "2003", value: "2003" },
  { label: "2002", value: "2002" },
  { label: "2001", value: "2001" },
  { label: "2000", value: "2000" },
  { label: "1999", value: "1999" },
  { label: "1998", value: "1998" },
  { label: "1997", value: "1997" },
  { label: "1996", value: "1996" },
  { label: "1995", value: "1995" },
  { label: "1994", value: "1994" },
  { label: "1993", value: "1993" },
  { label: "1992", value: "1992" },
  { label: "1991", value: "1991" },
  { label: "1990", value: "1990" },
  { label: "1989", value: "1989" },
  { label: "1988", value: "1988" },
  { label: "1987", value: "1987" },
  { label: "1986", value: "1986" },
  { label: "1985", value: "1985" },
  { label: "1984", value: "1984" },
  { label: "1983", value: "1983" },
  { label: "1982", value: "1982" },
  { label: "1981", value: "1981" },
  { label: "1980", value: "1980" },
  { label: "1979", value: "1979" },
  { label: "1978", value: "1978" },
  { label: "1977", value: "1977" },
  { label: "1976", value: "1976" },
  { label: "1975", value: "1975" },
  { label: "1974", value: "1974" },
  { label: "1973", value: "1973" },
  { label: "1972", value: "1972" },
  { label: "1971", value: "1971" },
  { label: "1970", value: "1970" },
  { label: "1969", value: "1969" },
  { label: "1968", value: "1968" },
  { label: "1967", value: "1967" },
  { label: "1966", value: "1966" },
  { label: "1965", value: "1965" },
  { label: "1964", value: "1964" },
  { label: "1963", value: "1963" },
  { label: "1962", value: "1962" },
  { label: "1961", value: "1961" },
  { label: "1960", value: "1960" },
  { label: "1959", value: "1959" },
  { label: "1958", value: "1958" },
  { label: "1957", value: "1957" },
  { label: "1956", value: "1956" },
  { label: "1955", value: "1955" },
  { label: "1954", value: "1954" },
  { label: "1953", value: "1953" },
  { label: "1952", value: "1952" },
  { label: "1951", value: "1951" },
  { label: "1950", value: "1950" },
  { label: "1949", value: "1949" },
  { label: "1948", value: "1948" },
  { label: "1947", value: "1947" },
  { label: "1946", value: "1946" },
  { label: "1945", value: "1945" },
  { label: "1944", value: "1944" },
  { label: "1943", value: "1943" },
  { label: "1942", value: "1942" },
  { label: "1941", value: "1941" },
  { label: "1940", value: "1940" },
  { label: "1939", value: "1939" },
  { label: "1938", value: "1938" },
  { label: "1937", value: "1937" },
  { label: "1936", value: "1936" },
  { label: "1935", value: "1935" },
  { label: "1934", value: "1934" },
  { label: "1933", value: "1933" },
  { label: "1932", value: "1932" },
  { label: "1931", value: "1931" },
  { label: "1930", value: "1930" },
  { label: "1929", value: "1929" },
  { label: "1928", value: "1928" },
  { label: "1927", value: "1927" },
  { label: "1926", value: "1926" },
  { label: "1925", value: "1925" },
  { label: "1924", value: "1924" },
  { label: "1923", value: "1923" },
  { label: "1922", value: "1922" },
  { label: "1921", value: "1921" },
  { label: "1920", value: "1920" },
  { label: "1919", value: "1919" },
  { label: "1918", value: "1918" },
  { label: "1917", value: "1917" },
  { label: "1916", value: "1916" },
  { label: "1915", value: "1915" },
  { label: "1914", value: "1914" },
  { label: "1913", value: "1913" },
  { label: "1912", value: "1912" },
  { label: "1911", value: "1911" },
  { label: "1910", value: "1910" },
  { label: "1909", value: "1909" },
  { label: "1908", value: "1908" },
  { label: "1907", value: "1907" },
  { label: "1906", value: "1906" },
  { label: "1905", value: "1905" },
  { label: "1904", value: "1904" },
  { label: "1903", value: "1903" }
];


export const activitiesData = [
  { label: "Student Council", value: "student_council" },
  { label: "Drama Club", value: "drama_club" },
  { label: "Debate Team", value: "debate_team" },
  { label: "Chess Club", value: "chess_club" },
  { label: "Science Club", value: "science_club" },
  { label: "Math Club", value: "math_club" },
  { label: "Robotics Club", value: "robotics_club" },
  { label: "Art Club", value: "art_club" },
  { label: "Band", value: "band" },
  { label: "Choir", value: "choir" },
  { label: "Orchestra", value: "orchestra" },
  { label: "Dance Team", value: "dance_team" },
  { label: "Yearbook Committee", value: "yearbook_committee" },
  { label: "Newspaper Club", value: "newspaper_club" },
  { label: "Environmental Club", value: "environmental_club" },
  { label: "Photography Club", value: "photography_club" },
  { label: "Coding Club", value: "coding_club" },
  { label: "Model United Nations", value: "model_united_nations" },
  { label: "Future Business Leaders of America (FBLA)", value: "fbla" },
  { label: "Key Club", value: "key_club" },
  { label: "National Honor Society", value: "national_honor_society" },
  { label: "Spanish Club", value: "spanish_club" },
  { label: "French Club", value: "french_club" },
  { label: "German Club", value: "german_club" },
  { label: "Chinese Club", value: "chinese_club" },
  { label: "Drama Society", value: "drama_society" },
  { label: "Peer Tutoring", value: "peer_tutoring" },
  { label: "Volunteer Club", value: "volunteer_club" },
  { label: "Health and Wellness Club", value: "health_wellness_club" },
  { label: "Fitness Club", value: "fitness_club" },
  { label: "History Club", value: "history_club" },
  { label: "Book Club", value: "book_club" },
  { label: "Film Club", value: "film_club" },
  { label: "Drama Society", value: "drama_society" },
  { label: "Glee Club", value: "glee_club" },
  { label: "Cooking Club", value: "cooking_club" },
  { label: "Fashion Club", value: "fashion_club" },
  { label: "Drama Society", value: "drama_society" },
  { label: "Future Farmers of America (FFA)", value: "ffa" },
  { label: "Junior Reserve Officers' Training Corps (JROTC)", value: "jrotc" },
  { label: "Quiz Bowl", value: "quiz_bowl" },
  { label: "Speech Team", value: "speech_team" },
  { label: "Student Government", value: "student_government" },
  { label: "Theater Club", value: "theater_club" },
  { label: "Astronomy Club", value: "astronomy_club" },
  { label: "Gardening Club", value: "gardening_club" },
  { label: "Anime Club", value: "anime_club" },
  { label: "Manga Club", value: "manga_club" },
  { label: "Cosplay Club", value: "cosplay_club" },
  { label: "Skateboarding Club", value: "skateboarding_club" },
  { label: "Surfing Club", value: "surfing_club" },
  { label: "Snowboarding Club", value: "snowboarding_club" },
  { label: "Rock Climbing Club", value: "rock_climbing_club" },
  { label: "Weightlifting Club", value: "weightlifting_club" },
  { label: "Soccer Club", value: "soccer_club" },
  { label: "Basketball Club", value: "basketball_club" },
  { label: "Baseball Club", value: "baseball_club" },
  { label: "Football Club", value: "football_club" },
  { label: "Tennis Club", value: "tennis_club" },
  { label: "Badminton Club", value: "badminton_club" },
  { label: "Table Tennis Club", value: "table_tennis_club" },
  { label: "Golf Club", value: "golf_club" },
  { label: "Archery Club", value: "archery_club" },
  { label: "Fencing Club", value: "fencing_club" },
  { label: "Horseback Riding Club", value: "horseback_riding_club" },
  { label: "Drama Society", value: "drama_society" },
  { label: "Music Production Club", value: "music_production_club" },
  { label: "DJ Club", value: "dj_club" },
  { label: "Videography Club", value: "videography_club" },
  { label: "Filmmaking Club", value: "filmmaking_club" },
  { label: "3D Modeling Club", value: "3d_modeling_club" },
  { label: "Animation Club", value: "animation_club" },
  { label: "Virtual Reality Club", value: "virtual_reality_club" },
  { label: "Augmented Reality Club", value: "augmented_reality_club" },
  { label: "Entrepreneurship Club", value: "entrepreneurship_club" },
  { label: "Public Speaking Club", value: "public_speaking_club" },
  { label: "Debate Club", value: "debate_club" }
];


export const statesData = [
  { label: "Alabama", value: "AL" },
  { label: "Alaska", value: "AK" },
  { label: "Arizona", value: "AZ" },
  { label: "Arkansas", value: "AR" },
  { label: "California", value: "CA" },
  { label: "Colorado", value: "CO" },
  { label: "Connecticut", value: "CT" },
  { label: "Delaware", value: "DE" },
  { label: "Florida", value: "FL" },
  { label: "Georgia", value: "GA" },
  { label: "Hawaii", value: "HI" },
  { label: "Idaho", value: "ID" },
  { label: "Illinois", value: "IL" },
  { label: "Indiana", value: "IN" },
  { label: "Iowa", value: "IA" },
  { label: "Kansas", value: "KS" },
  { label: "Kentucky", value: "KY" },
  { label: "Louisiana", value: "LA" },
  { label: "Maine", value: "ME" },
  { label: "Maryland", value: "MD" },
  { label: "Massachusetts", value: "MA" },
  { label: "Michigan", value: "MI" },
  { label: "Minnesota", value: "MN" },
  { label: "Mississippi", value: "MS" },
  { label: "Missouri", value: "MO" },
  { label: "Montana", value: "MT" },
  { label: "Nebraska", value: "NE" },
  { label: "Nevada", value: "NV" },
  { label: "New Hampshire", value: "NH" },
  { label: "New Jersey", value: "NJ" },
  { label: "New Mexico", value: "NM" },
  { label: "New York", value: "NY" },
  { label: "North Carolina", value: "NC" },
  { label: "North Dakota", value: "ND" },
  { label: "Ohio", value: "OH" },
  { label: "Oklahoma", value: "OK" },
  { label: "Oregon", value: "OR" },
  { label: "Pennsylvania", value: "PA" },
  { label: "Rhode Island", value: "RI" },
  { label: "South Carolina", value: "SC" },
  { label: "South Dakota", value: "SD" },
  { label: "Tennessee", value: "TN" },
  { label: "Texas", value: "TX" },
  { label: "Utah", value: "UT" },
  { label: "Vermont", value: "VT" },
  { label: "Virginia", value: "VA" },
  { label: "Washington", value: "WA" },
  { label: "West Virginia", value: "WV" },
  { label: "Wisconsin", value: "WI" },
  { label: "Wyoming", value: "WY" }
];


export const jobFieldsData = [
  { label: "Accounting", value: "Accounting" },
  { label: "Administration", value: "Administration" },
  { label: "Advertising", value: "Advertising" },
  { label: "Agriculture", value: "Agriculture" },
  { label: "Architecture", value: "Architecture" },
  { label: "Arts", value: "Arts" },
  { label: "Banking", value: "Banking" },
  { label: "Construction", value: "Construction" },
  { label: "Consulting", value: "Consulting" },
  { label: "Customer Service", value: "Customer Service" },
  { label: "Education", value: "Education" },
  { label: "Engineering", value: "Engineering" },
  { label: "Entertainment", value: "Entertainment" },
  { label: "Finance", value: "Finance" },
  { label: "Food Service", value: "Food Service" },
  { label: "Healthcare", value: "Healthcare" },
  { label: "Human Resources", value: "Human Resources" },
  { label: "Information Technology", value: "Information Technology" },
  { label: "Insurance", value: "Insurance" },
  { label: "Legal", value: "Legal" },
  { label: "Manufacturing", value: "Manufacturing" },
  { label: "Marketing", value: "Marketing" },
  { label: "Media", value: "Media" },
  { label: "Nonprofit", value: "Nonprofit" },
  { label: "Public Relations", value: "Public Relations" },
  { label: "Real Estate", value: "Real Estate" },
  { label: "Retail", value: "Retail" },
  { label: "Sales", value: "Sales" },
  { label: "Science", value: "Science" },
  { label: "Social Media", value: "Social Media" },
  { label: "Sports", value: "Sports" },
  { label: "Telecommunications", value: "Telecommunications" },
  { label: "Transportation", value: "Transportation" },
  { label: "Travel", value: "Travel" },
];



export const collegesData = [
  { label: "Harvard University", value: "harvard_university" },
  { label: "Stanford University", value: "stanford_university" },
  { label: "Massachusetts Institute of Technology (MIT)", value: "mit" },
  { label: "California Institute of Technology (Caltech)", value: "caltech" },
  { label: "University of Cambridge", value: "university_of_cambridge" },
  { label: "University of Oxford", value: "university_of_oxford" },
  { label: "Princeton University", value: "princeton_university" },
  { label: "Yale University", value: "yale_university" },
  { label: "Columbia University", value: "columbia_university" },
  { label: "University of Chicago", value: "university_of_chicago" },
  { label: "University of Pennsylvania", value: "university_of_pennsylvania" },
  { label: "Northwestern University", value: "northwestern_university" },
  { label: "Duke University", value: "duke_university" },
  { label: "Johns Hopkins University", value: "johns_hopkins_university" },
  { label: "University of Michigan, Ann Arbor", value: "university_of_michigan" },
  { label: "Cornell University", value: "cornell_university" },
  { label: "University of California, Berkeley", value: "university_of_california_berkeley" },
  { label: "University of California, Los Angeles (UCLA)", value: "university_of_california_los_angeles" },
  { label: "University of California, San Diego (UCSD)", value: "university_of_california_san_diego" },
  { label: "University of California, Davis (UC Davis)", value: "university_of_california_davis" },
  { label: "University of California, Irvine (UC Irvine)", value: "university_of_california_irvine" },
  { label: "University of California, Santa Barbara (UCSB)", value: "university_of_california_santa_barbara" },
  { label: "University of California, Santa Cruz (UCSC)", value: "university_of_california_santa_cruz" },
  { label: "University of Southern California (USC)", value: "university_of_southern_california" },
  { label: "New York University (NYU)", value: "new_york_university" },
  { label: "Brown University", value: "brown_university" },
  { label: "Dartmouth College", value: "dartmouth_college" },
  { label: "Vanderbilt University", value: "vanderbilt_university" },
  { label: "Emory University", value: "emory_university" },
  { label: "Rice University", value: "rice_university" },
  { label: "University of Notre Dame", value: "university_of_notre_dame" },
  { label: "Georgetown University", value: "georgetown_university" },
  { label: "University of Virginia", value: "university_of_virginia" },
  { label: "Carnegie Mellon University", value: "carnegie_mellon_university" },
  { label: "University of Washington", value: "university_of_washington" },
  { label: "University of Texas at Austin", value: "university_of_texas_at_austin" },
  { label: "University of Florida", value: "university_of_florida" },
  { label: "University of Wisconsin-Madison", value: "university_of_wisconsin_madison" },
  { label: "University of Illinois at Urbana-Champaign", value: "university_of_illinois_at_urbana_champaign" },
  { label: "University of North Carolina at Chapel Hill", value: "university_of_north_carolina_at_chapel_hill" },
  { label: "University of Georgia", value: "university_of_georgia" },
  { label: "University of Miami", value: "university_of_miami" },
  { label: "Boston University", value: "boston_university" },
  { label: "University of Maryland, College Park", value: "university_of_maryland_college_park" },
  { label: "University of Pittsburgh", value: "university_of_pittsburgh" },
  { label: "Purdue University", value: "purdue_university" },
  { label: "University of Minnesota Twin Cities", value: "university_of_minnesota_twin_cities" },
  { label: "Ohio State University", value: "ohio_state_university" },
  { label: "University of Arizona", value: "university_of_arizona" },
  { label: "University of Colorado Boulder", value: "university_of_colorado_boulder" },
  { label: "University of Utah", value: "university_of_utah" },
  { label: "University of Oregon", value: "university_of_oregon" },
  { label: "Arizona State University", value: "arizona_state_university" },
  { label: "University of Houston", value: "university_of_houston" },
  { label: "University of Massachusetts Amherst", value: "university_of_massachusetts_amherst" },
  { label: "University of Connecticut", value: "university_of_connecticut" },
  { label: "University of South Carolina", value: "university_of_south_carolina" },
  { label: "University of Tennessee Knoxville", value: "university_of_tennessee_knoxville" },
  { label: "Michigan State University", value: "michigan_state_university" },
  { label: "Texas A&M University", value: "texas_a&m_university" },
  { label: "Indiana University Bloomington", value: "indiana_university_bloomington" },
  { label: "University of Kentucky", value: "university_of_kentucky" },
  { label: "Iowa State University", value: "iowa_state_university" },
  { label: "University of Oklahoma", value: "university_of_oklahoma" },
  { label: "University of Alabama", value: "university_of_alabama" },
  { label: "Louisiana State University", value: "louisiana_state_university" },
  { label: "University of Iowa", value: "university_of_iowa" },
  { label: "University of Mississippi", value: "university_of_mississippi" },
  { label: "University of Nebraska Lincoln", value: "university_of_nebraska_lincoln" },
  { label: "University of Nevada Las Vegas", value: "university_of_nevada_las_vegas" },
  { label: "University of New Hampshire", value: "university_of_new_hampshire" },
  { label: "University of New Mexico", value: "university_of_new_mexico" },
  { label: "University of Rhode Island", value: "university_of_rhode_island" },
  { label: "University of South Florida", value: "university_of_south_florida" },
  { label: "University of Vermont", value: "university_of_vermont" },
  { label: "University of Wyoming", value: "university_of_wyoming" },
];


export const departmentsData = [
  { label: "Art", value: "art" },
  { label: "Biology", value: "biology" },
  { label: "Chemistry", value: "chemistry" },
  { label: "Computer Science", value: "computer_science" },
  { label: "English", value: "english" },
  { label: "History", value: "history" },
  { label: "Mathematics", value: "mathematics" },
  { label: "Music", value: "music" },
  { label: "Physical Education", value: "physical_education" },
  { label: "Physics", value: "physics" },
  { label: "Psychology", value: "psychology" },
  { label: "Sociology", value: "sociology" },
  { label: "Technology", value: "technology" },
  { label: "Administration", value: "administration" },
  { label: "Counseling", value: "counseling" },
  { label: "Librarian", value: "librarian" },
  { label: "Nurse", value: "nurse" },
  { label: "Special Education", value: "special_education" },
];


export const groupCategories = [
  { label: "Technology", value: "Technology" },
  { label: "Arts", value: "Arts" },
  { label: "Athletic", value: "Athletic" },
  { label: "Academic", value: "Academic" },
  { label: "Faith, Justice, Wellness", value: "Faith, Justice, Wellness" },
  { label: "General", value: "General" },

]



export const roles = [
  { label: "Student", value: "Student" },
  { label: "Faculty/Staff", value: "Faculty/Staff" },
  { label: "Alumni", value: "Alumni" },
  { label: "Parent", value: "Parent" }, 
  { label: "Guest", value: "Guest" }

]